# Generated by Django 3.0.5 on 2020-05-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Прошел активацию?'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='send_message',
            field=models.BooleanField(default=True, verbose_name='Слать оповещения о новых коментариях?'),
        ),
    ]
