# Generated by Django 3.0.5 on 2020-05-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200514_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subrubric',
            options={'ordering': ('super_rubric__order', 'super_rubric__name', 'order', 'name'), 'verbose_name': 'Подрубрика', 'verbose_name_plural': 'Подрубрики'},
        ),
    ]
