# Generated by Django 3.0.5 on 2020-05-27 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerOfLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'follower_of_lesson',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название урока')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('published', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор урока')),
                ('followers', models.ManyToManyField(related_name='_lesson_followers_+', through='main.FollowerOfLesson', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики на урок')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='LesonTube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250, verbose_name='Название видео-урока')),
                ('path_file', models.FileField(upload_to='', verbose_name='Видео-урок')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор урока')),
            ],
            options={
                'verbose_name': 'Видео-урок',
                'verbose_name_plural': 'Видео-уроки',
            },
        ),
        migrations.AddField(
            model_name='followeroflesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lesson'),
        ),
        migrations.AddField(
            model_name='followeroflesson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advuser',
            name='lessons',
            field=models.ManyToManyField(related_name='_advuser_lessons_+', through='main.FollowerOfLesson', to='main.Lesson', verbose_name='Доступные уроки'),
        ),
    ]
