# Generated by Django 3.0.5 on 2020-05-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200522_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=999999.99, max_digits=10, verbose_name='Цена продажи'),
            preserve_default=False,
        ),
    ]
