# Generated by Django 3.0.5 on 2020-05-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20200521_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'My Subscriber', 'verbose_name_plural': 'A lot of subscribers'},
        ),
    ]
